fix(FEC 11051):
kaltura/kaltura-player-youi pull request #46
Opened 2021-03-02 15:49 UTC by giladna

2021-03-02 17:57 UTC, OrenMe requested changes

2021-03-02 17:57 UTC, OrenMe commented on youi/src/player/KalturaVideoPlayer.h
> +    CYISignal<float> PlayerZIndexChangedEvent;
we can remove this

2021-03-03 08:45 UTC, giladna commented on youi/src/player/KalturaVideoPlayer.h
> +    CYISignal<float> PlayerZIndexChangedEvent;
done

2021-03-03 08:53 UTC, OrenMe approved these changes

2021-03-03 10:13 UTC, merged